export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MEASSAGE';
export const DELETE_MESSAGES = 'DELETE_MESSAGES';
export const ADD_REMOVE_LABELS = 'ADD_REMOVE_LABELS';
export const UPDATE_READ_MESSAGES = 'UPDATE_READ_MESSAGES';
export const UPDATE_STARRED_MESSAGE = 'UPDATE_STARRED_MESSAGE';

export const MESSAGE_SELECTED = 'MESSAGE_SELECTED';
export const BULK_MESSAGE_SELECTED = 'BULK_MESSAGE_SELECTED';

export const TOGGEL_COMPOSED_FORM = 'TOGGEL_COMPOSED_FORM';
