export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const GET_MESSAGE_BODY = 'GET_MESSAGE_BODY';

export const ADD_LABELS = 'ADD_LABELS';
export const REMOVE_LABELS = 'REMOVE_LABELS';

export const CREATE_MESSAGE = 'CREATE_MEASSAGE';
export const DELETE_MESSAGES = 'DELETE_MESSAGES';

export const UPDATE_READ_MESSAGES = 'UPDATE_READ_MESSAGES';
export const UPDATE_STARRED_MESSAGE = 'UPDATE_STARRED_MESSAGE';

export const BULK_MESSAGE_SELECTED = 'BULK_MESSAGE_SELECTED';
export const TOGGLE_MESSAGE_SELECTED = 'TOGGLE_MESSAGE_SELECTED';

export const TOGGEL_COMPOSED_FORM = 'TOGGEL_COMPOSED_FORM';
